### ISSUE TITLE
Why doesn't it work like the video？

### ISSUE THREAD

**Issue by heimawsw** [WassimTenachi/PhySO#10]
I successfully ran the program unit test, but could not achieve the dynamic effect in the video.
**How is the effect achieved in the video?**

https://user-images.githubusercontent.com/63928316/225642347-a07127da-a84e-4af3-96f4-4c7fef5a673b.mp4

![image](https://user-images.githubusercontent.com/29699353/225838193-2a7757f6-3927-4458-9925-be3619bf5185.png)

**Is there a python program that needs to be run?**

**Comment by WassimTenachi** [comment]
Hi @heimawsw,

PhySO is a symbolic regression package aiming at discovering physical laws from datasets.
The screenshot that you sent is the output of the units tests, not a proper symbolic regression task on a dataset.

You should run the damped harmonic oscillator notebook, it will output a live monitoring plot + a log that will contain an even more informative record of what's going on during the symbolic regression task.

**Comment by heimawsw** [comment]
![image](https://user-images.githubusercontent.com/29699353/225945543-1653bbad-f470-4c5f-85cc-d9c95dae6b2c.png)

When I run python demo_damped_harmonic_oscillator.py, the panel opens, but there are many errors. Below is the log, please help to analyze the problem.


`
C:\Users\Administrator\Desktop\wsw\PhySO-main\demo\demo_damped_harmonic_oscillator>conda activate PhySO

(PhySO) C:\Users\Administrator\Desktop\wsw\PhySO-main\demo\demo_damped_harmonic_oscillator>python demo_damped_harmonic_oscillator.py
cpu
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\texmanager.py", line 233, in _run_checked_subprocess
    report = subprocess.check_output(
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\backends\backend_qt.py", line 455, in _draw_idle
    self.draw()
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\backends\backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\figure.py", line 2810, in draw
    mimage._draw_list_compositing_images(
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\axes\_base.py", line 3082, in draw
    mimage._draw_list_compositing_images(
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\axis.py", line 1159, in draw
    ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\axis.py", line 1085, in _get_tick_bboxes
    return ([tick.label1.get_window_extent(renderer)
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\axis.py", line 1085, in <listcomp>
    return ([tick.label1.get_window_extent(renderer)
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\text.py", line 910, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\text.py", line 309, in _get_layout
    _, lp_h, lp_d = renderer.get_text_width_height_descent(
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\backends\backend_agg.py", line 259, in get_text_width_height_descent
    w, h, d = texmanager.get_text_width_height_descent(
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\texmanager.py", line 335, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\texmanager.py", line 271, in make_dvi
    self._run_checked_subprocess(
  File "D:\ProgramData\Anaconda3\envs\PhySO\lib\site-packages\matplotlib\texmanager.py", line 237, in _run_checked_subprocess
    raise RuntimeError(
RuntimeError: Failed to process string with tex because latex could not be found
`

**Comment by WassimTenachi** [comment]
Hi @heimawsw,

To convert an expression in the log into a more good looking latex expression, you can use this snippet:

`
import sympy
import matplotlib.pyplot as plt

expr_str = "(sin(((f*t)+phi))*exp((alpha*-(t))))+1-1"

# Getting a sympy expression
expr_sympy = sympy.parsing.sympy_parser.parse_expr(expr_str, evaluate=False)

# If you want the simplified version
expr_sympy = sympy.simplify(expr_sympy, rational=True)

# Getting a latex expression
expr_latex = sympy.latex (expr_sympy)

# Getting a figure containing expression
#plt.rc('text', usetex=True)
#plt.rc('font', family='serif')
#plt.rc('text.latex', preamble=r'\usepackage{amssymb} \usepackage{xcolor}')
fig, ax = plt.subplots(1, 1, figsize=(10, 2))
ax.axis('off')
text_pos = (0.0, 0.5)
ax.text(text_pos[0], text_pos[1], f'${expr_latex}$', size = 16)

plt.show()
`

That's what I used to make the demo video !

**Comment by heimawsw** [comment]
Thank you very much for the ideas provided by the author, I am now successfully running python as expected. In the future, I will learn how to optimize machine learning time. Currently, data processing is very slow.
